#!/bin/bash

read n
sum=0
for ((i=0; i<n; i++))
do
read y
 sum=$((y + sum))
done
#avg="$sum/$n" | bc -l #error- for basic calculator option there no output from bascic calculator
avg=$(echo "$sum/$n" | bc -l )
printf "%.3f" "$avg"
